composer require drupal/gutenberg
composer require drupal/feeds:3.x-dev
composer require drupal/tamper:1.x-dev
composer require drupal/feeds_tamper:2.x-dev
composer require drupal/cdn
composer require drupal/stage_file_proxy
composer require drupal/fontawesome
composer require drupal/advagg
composer require drupal/bootstrap_library
composer require drupal/media_library_theme_reset
composer require drupal/field_group
composer require drupal/bootstrap_layouts
composer require drupal/layout_builder_admin_theme
composer require drupal/webform
composer require drupal/views_taxonomy_term_name_depth
composer require drupal/views_fieldsets
composer require oomphinc/composer-installers-extender
composer require drupal/jquery_ui_touch_punch
composer require npm-asset/jquery-ui-touch-punch
composer require drupal/better_exposed_filters
composer require drupal/metatag
composer require drupal/token
composer require drupal/scheduler:2.x-dev
composer require drupal/redirect
composer require drupal/pathauto
composer require drupal/media_library_form_element
composer require drupal/libraries:3.x-dev
composer require drupal/extra_css_js
composer require drupal/addtocal:2.x-dev
composer require drupal/svg_image
composer require drupal/image_widget_crop
composer require drupal/focal_point
composer require drupal/crop
composer require drupal/bootstrap_layout_builder
composer require drupal/bootstrap_styles
composer require drupal/layout_builder_base:1.x-dev
composer require drupal/layout_builder_blocks
composer require drupal/layout_builder_styles:1.x-dev
composer require drupal/config_filter
composer require drupal/config_split:2.0.x-dev
composer require drupal/gutenberg_bs_blocks:1.0.0-rc1
composer require drupal/address