drush en -y gutenberg
drush en -y feeds
drush en -y tamper
drush en -y feeds_tamper
drush en -y cdn
drush en -y stage_file_proxy
drush en -y fontawesome
drush en -y advagg
drush en -y bootstrap_library
drush en -y media_library_theme_reset
drush en -y field_group
drush en -y bootstrap_layouts
drush en -y layout_builder_admin_theme
drush en -y webform
drush en -y views_taxonomy_term_name_depth
drush en -y views_fieldsets
drush en -y better_exposed_filters
drush en -y metatag
drush en -y token
drush en -y scheduler
drush en -y redirect
drush en -y pathauto
drush en -y media_library_form_element
drush en -y libraries
drush en -y extra_css_js
drush en -y addtocal
drush en -y svg_image
drush en -y image_widget_crop
drush en -y focal_point
drush en -y crop
drush en -y bootstrap_layout_builder
drush en -y bootstrap_styles
drush en -y layout_builder_base
drush en -y layout_builder_blocks
drush en -y layout_builder_styles
drush en -y config_filter
drush en -y config_split
drush en -y gutenberg_bs_blocks
drush en -y address
cd /var/www/drupal/web/sites/default
chmod 777 -R files