_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  action: 0
  address: 0
  automated_cron: 0
  basic_auth: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cdn: 0
  cdn_ui: 0
  ckeditor: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  extra_css_js: 0
  facets: 0
  facets_rest: 0
  facets_searchbox_widget: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  fontawesome_media: 0
  gatsby_extras: 0
  geolocation: 0
  gin_toolbar: 0
  help: 0
  help_topics: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  language: 0
  layout_builder: 0
  layout_builder_admin_theme: 0
  layout_builder_base: 0
  layout_builder_base_library: 0
  layout_builder_styles: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  react_webform_backend: 0
  responsive_image: 0
  rest: 0
  search: 0
  search_api: 0
  search_api_db: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  slick: 0
  slick_ui: 0
  sqlite: 0
  stage_file_proxy: 0
  statistics: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tracker: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_data_export: 0
  views_fieldsets: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  workspaces: 0
  pathauto: 1
  content_translation: 10
  views: 10
  gatsby: 100
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
profile: standard
