module:
  action: 0
  address: 0
  addtocal: 0
  advagg: 0
  aggregator: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layout_builder: 0
  bootstrap_layouts: 0
  bootstrap_library: 0
  bootstrap_styles: 0
  breakpoint: 0
  cdn: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  extra_css_js: 0
  feeds: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  gutenberg: 0
  gutenberg_bs_blocks: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  layout_builder: 0
  layout_builder_admin_theme: 0
  layout_builder_base: 0
  layout_builder_blocks: 0
  layout_builder_styles: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  scheduler: 0
  search: 0
  shortcut: 0
  stage_file_proxy: 0
  svg_image: 0
  system: 0
  tamper: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_fieldsets: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  webform: 0
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
